<a href="https://colab.research.google.com/github/manikdey77/manikdey77/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

In [5]:
from google.colab import files
uploaded = files.upload()

Saving Return_2018_2025.csv to Return_2018_2025.csv

In [7]:
for fn in uploaded.keys():
  print(f'User uploaded file "{fn}"')
  # Example to read a CSV file into a DataFrame
  # df = pd.read_csv(io.BytesIO(uploaded[fn]))

User uploaded file "Return_2018_2025.csv"

In [8]:
import pandas as pd
import io

for fn in uploaded.keys():
    print(f'User uploaded file "{fn}"')
    data = pd.read_csv(io.BytesIO(uploaded[fn]))

User uploaded file "Return_2018_2025.csv"

In [9]:
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1622 entries, 0 to 1621
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1622 non-null   object
 1   BTC     1622 non-null   float64
 2   ETH     1622 non-null   float64
 3   BNB     1622 non-null   float64
 4   SP500   1622 non-null   float64
 5   NASDAQ  1622 non-null   float64
 6   NIFTY   1622 non-null   float64
 7   EURUSD  1622 non-null   float64
 8   USDINR  1622 non-null   float64
 9   USDJPY  1622 non-null   float64
dtypes: float64(9), object(1)
memory usage: 126.8+ KB

In [10]:
data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%Y')

In [11]:
data.set_index('Date', inplace=True)
data.sort_index(inplace=True)

In [12]:
print(data.index[:5])
print(data.index.dtype)

DatetimeIndex(['2018-04-03', '2018-04-04', '2018-04-05', '2018-04-09',
               '2018-04-10'],
              dtype='datetime64[ns]', name='Date', freq=None)
datetime64[ns]

In [13]:
print(data.isna().sum())

BTC       0
ETH       0
BNB       0
SP500     0
NASDAQ    0
NIFTY     0
EURUSD    0
USDINR    0
USDJPY    0
dtype: int64

In [131]:
series = data[['USDJPY']].dropna().copy()

In [132]:
print(series.shape)
print(series.head())

(1622, 1)
              USDJPY
Date
2018-04-03  0.006003
2018-04-04  0.003171
2018-04-05  0.002600
2018-04-09 -0.002834
2018-04-10  0.003404

In [49]:
def create_sequences(series, lookback):
    X, y = [], []
    for i in range(lookback, len(series)):
        X.append(series[i-lookback:i])
        y.append(series[i])
    return np.array(X), np.array(y)

In [133]:
lookback = 80
initial_train_size = 500

train_series = series.iloc[:initial_train_size]

scaler = StandardScaler()
scaled_train = scaler.fit_transform(train_series.values)

X_train, y_train = create_sequences(scaled_train, lookback)
X_train = X_train.reshape((X_train.shape[0], lookback, 1))

model = Sequential()

model.add(LSTM(64, return_sequences=True,
               dropout=0.2,
               input_shape=(lookback,1)))

model.add(LSTM(32, dropout=0.2))

model.add(Dense(16, activation='relu'))  # nonlinear projection
model.add(Dense(1))

model.compile(optimizer=Adam(learning_rate=0.0005),
              loss='huber')

model.fit(X_train, y_train,
          epochs=50,
          batch_size=16,
          verbose=1)

Epoch 1/50

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

27/27 ━━━━━━━━━━━━━━━━━━━━ 6s 84ms/step - loss: 0.3534
Epoch 2/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.3742
Epoch 3/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - loss: 0.3985
Epoch 4/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3327
Epoch 5/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3422
Epoch 6/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - loss: 0.4022
Epoch 7/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3405
Epoch 8/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - loss: 0.3146
Epoch 9/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 61ms/step - loss: 0.3903
Epoch 10/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - loss: 0.3899
Epoch 11/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - loss: 0.3596
Epoch 12/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3638
Epoch 13/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - loss: 0.3582
Epoch 14/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - loss: 0.3734
Epoch 15/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - loss: 0.3457
Epoch 16/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - loss: 0.3597
Epoch 17/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - loss: 0.3584
Epoch 18/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3837
Epoch 19/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - loss: 0.3488
Epoch 20/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - loss: 0.3598
Epoch 21/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3784
Epoch 22/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3438
Epoch 23/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.3683
Epoch 24/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - loss: 0.3654
Epoch 25/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.3874
Epoch 26/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3682
Epoch 27/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - loss: 0.3703
Epoch 28/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - loss: 0.3598
Epoch 29/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.4062
Epoch 30/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3546
Epoch 31/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 76ms/step - loss: 0.3533
Epoch 32/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.3724
Epoch 33/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - loss: 0.3435
Epoch 34/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.3772
Epoch 35/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - loss: 0.4002
Epoch 36/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.3517
Epoch 37/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 84ms/step - loss: 0.4083
Epoch 38/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - loss: 0.3711
Epoch 39/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3580
Epoch 40/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - loss: 0.3275
Epoch 41/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - loss: 0.3391
Epoch 42/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - loss: 0.3338
Epoch 43/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - loss: 0.3551
Epoch 44/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 107ms/step - loss: 0.3421
Epoch 45/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.3220
Epoch 46/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - loss: 0.3757
Epoch 47/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 67ms/step - loss: 0.3716
Epoch 48/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.3727
Epoch 49/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.3511
Epoch 50/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.3622

In [134]:
predictions = []
actuals = []
dates = []

scaled_full = scaler.transform(series.values)

for t in range(initial_train_size, len(series)):

    input_seq = scaled_full[t-lookback:t]
    input_seq = input_seq.reshape((1, lookback, 1))

    forecast_scaled = model.predict(input_seq, verbose=0)
    forecast = scaler.inverse_transform(forecast_scaled)[0][0]

    predictions.append(forecast)
    actuals.append(series.iloc[t].values[0])
    dates.append(series.index[t])

In [135]:
results = pd.DataFrame({
    "Raw_Return": actuals,
    "Predictable_Component": predictions
}, index=dates)

results["Innovation_Component"] = (
    results["Raw_Return"] - results["Predictable_Component"]
)

In [136]:
results.head()

            Raw_Return  Predictable_Component  Innovation_Component
2020-09-02    0.002942               0.000296              0.002646
2020-09-03   -0.001149               0.000148             -0.001297
2020-09-08   -0.001113               0.000195             -0.001308
2020-09-09    0.002479               0.000222              0.002257
2020-09-10   -0.000829               0.000123             -0.000952

In [137]:
results.describe()

        Raw_Return  Predictable_Component  Innovation_Component
count  1122.000000            1122.000000           1122.000000
mean      0.000345              -0.000173              0.000518
std       0.006509               0.002185              0.006903
min      -0.037961              -0.010896             -0.041616
25%      -0.003066              -0.000591             -0.002911
50%       0.000448              -0.000036              0.000700
75%       0.003775               0.000452              0.004256
max       0.028645               0.007509              0.037095

In [138]:
(np.abs(results["Raw_Return"] -
        (results["Predictable_Component"] +
         results["Innovation_Component"])) < 1e-8).all()

np.True_

In [139]:
results.to_csv("usdjpy_lstm_decomposition.csv")

In [140]:
from google.colab import files
files.download("usdjpy_lstm_decomposition.csv")

In [60]:
from statsmodels.stats.diagnostic import acorr_ljungbox
acorr_ljungbox(results["Innovation_Component"], lags=[10], return_df=True)

     lb_stat  lb_pvalue
10  9.598359   0.476408

In [61]:
from statsmodels.stats.diagnostic import acorr_ljungbox

acorr_ljungbox(
    results["Raw_Return"],
    lags=[10],
    return_df=True
)

     lb_stat  lb_pvalue
10  7.839205    0.64454

In [141]:
acorr_ljungbox(results["Innovation_Component"], lags=[5,10,15,20])

       lb_stat     lb_pvalue
5   126.267834  1.473408e-25
10  200.548733  1.240053e-37
15  239.890228  1.491881e-42
20  250.280987  1.002586e-41